version: "3"

services:
  outer-openresty:
    image: openresty/openresty:latest
    ports:
      - "${HTTPBIN_PORT}:80"
    depends_on:
      - inner-openresty
    volumes:
      - "${HTTPBIN_ROOT_PATH}/config/common_config/:/etc/nginx/common_config/"
      - "${HTTPBIN_ROOT_PATH}/config/outer_nginx/:/etc/nginx/conf.d/"
      - "${HTTPBIN_ROOT_PATH}/config/outer_nginx/logs/:/var/httpbin_logs/"
    environment:
      - TZ=Asia/Shanghai # 将时区设置为上海
    networks:
      default:

  inner-openresty:
    image: openresty/openresty:latest
    depends_on:
      - httpbin-server
    volumes:
      - "${HTTPBIN_ROOT_PATH}/config/common_config/:/etc/nginx/common_config/"
      - "${HTTPBIN_ROOT_PATH}/config/inner_nginx/:/etc/nginx/conf.d/"
      - "${HTTPBIN_ROOT_PATH}/config/inner_nginx/logs/:/var/httpbin_logs/"
    environment:
      - TZ=Asia/Shanghai # 将时区设置为上海
    networks:
      default:

  httpbin-server:
    image: kennethreitz/httpbin
    ports:
      - "${HTTPBIN_ORIGINAL_PORT}:80"
    environment:
      - TZ=Asia/Shanghai # 将时区设置为上海
    networks:
      - default
